sudo: required
services:
        - docker

before_install:
        - docker build -t mavsvl/docker-react -f Dockerfile.dev .

script:
        - docker run mavsvl/docker-react npm run test -- --coverage
