sudo: required
services:
        - docker-compose

before_install:
        - docker-compose build tests

script:
        - docker-compose run --rm tests

deploy:
        provider: elasticbeanstalk
        region: "eu-west-1"
        app: "docker-react"
        env: "DockerReact-env"
        bucket_name: "elasticbeanstalk-eu-west-1-728900069172"
        bucket_path: "docker-react"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: 
                secure: "$AWS_SECRET_KEY"
